config/routes.rb
Rails.application.routes.draw do
  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'registrations'
  }

  resources :track_templates, except: [:edit] do
    resources :section_templates
  end

  resources :tracks, only: [] do
    resources :section_interactions, only: [:create, :edit, :update] do
      resources :todos
      resources :questions
    end
  end

  resources :mentoring_tracks, only: [:new, :create, :index, :show]
  resources :organizations, only: [:update]

  get 'users/auth/failure', to: redirect('/')
  get 'board', to: 'board#index'
  get 'home', to: 'board#home_page', as: 'home_page'
  get '/user/:mentee_id', to: 'mentoring_tracks#get_user_data'

  get '/organization', to: 'organizations#edit', as: 'edit_organization'
  get '/organization/invites', to: 'organizations#invite_members',
                               as: 'invite_organization_members'

  post '/organization/invite', to: 'organizations#invite', as: 'send_invitation'
  post '/requests', to: 'mentoring_requests#create'
  put '/requests/:id', to: 'mentoring_requests#update'

  root to: 'board#index'
end

app/views/layouts/_header.html.haml
- board_view ||= false

- if user_signed_in?
  %header
    = link_to root_path, class: 'navbar__org' do
      -if current_user
        %label.org-name  #{current_user.organization.name}
    .header__wrapper
      - if user_signed_in?
        - if board_view
          .menu{"ng-model" => "active_tab"}
            .menu__item{"ng-class" => "active_tab == 'user_tracks' ? 'active': 'inactive' ", "ng-click" => "change_tab('user_tracks', $event)"}
              %a{:href => ""} Learning tracks
              %span.notification-dot{"ng-if" => "actionTodoForMyTracks()"}
            .menu__item{"ng-class" => "active_tab == 'user_mentee_tracks' ? 'active': 'inactive' ", "ng-click" => "change_tab('user_mentee_tracks', $event)"}
              %a{:href => ""} Mentoring tracks
              %span.notification-dot{"ng-if" => "actionTodoForMyMenteeTracks()"}
            .menu__item{class: active_class(c: ['tracks'])}
              %a{:href => "/track_templates"} All tracks
        - else
          .menu
            .menu__item
              %a{:href => "", :class => "user_tracks"} Learning tracks
            .menu__item
              %a{:href => "", :class => "user_mentee_tracks"} Mentoring tracks
            .menu__item
              %a{:href => "/track_templates", :class => "tracks", :style => "display: inline;", class: track_template_active_class(c: ['track_templates'])} All tracks


        - if user_signed_in?
          %ul.userProfile
            -if current_user.image.present?
              %li.userProfile__image= image_tag current_user.image
            -else
              %li.userProfile__image= gravatar_for current_user
            %li.userProfile__name.drop
              = current_user.first_name
              %i.material-icons arrow_drop_down
              %ul
                %li
                  =link_to "Dashboard", mentoring_tracks_path, class: active_class(c:  ['mentoring_tracks'])
                  %span.notification-dot{"ng-if" => "notificationForNewMenteeRequests()"}
                %li= link_to current_user.email.split('@')[1].split('.')[0], invite_organization_members_path
                %hr
                %li= link_to "Log out", destroy_user_session_path, method: :delete
        - else
          %ul
            %li= link_to "Login", new_user_session_path
            %li
              %button= link_to "Sign Up", new_user_registration_path

:javascript
    $(function() {
      $('.user_tracks').on('click', function(e) {
        e.preventDefault();
        sessionStorage.setItem('tab', 'user_tracks');
        window.location = '/';
      })
      $('.user_mentee_tracks').on('click', function(e) {
        e.preventDefault();
        sessionStorage.setItem('tab', 'user_mentee_tracks');
        window.location = '/';
      })
    });

app/views/layouts/application.html.haml
!!!
%html{:lang => 'en', 'ng-app' => 'mentorhub', :class => 'no-js'}
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title MentorHub
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = action_cable_meta_tag
    = csrf_meta_tags
    %link{:href => "//fonts.googleapis.com/css?family=Open+Sans", :rel => "stylesheet", :type => "text/css"}/
  %body
    :javascript
      $(document).ready(function(){
        setTimeout(function(){
          $(".flash_message" ).fadeOut("slow");
        }, 5000);
      })

      var PageConfig = {};

    = render 'layouts/header'

    - if breadcrumbs.present?
      .bread_crumbs
        = breadcrumbs style: :bootstrap,class:""

    - flash.each do |message_type, message|
      - unless message_type.to_s == 'timedout'
        %div{:class => "flash_message alert alert-#{message_type}"}= message

    = yield